name: build

on:
  # Trigger the workflow on push or pull request
  push:
    branches:
      - feat/*
      - feature/*
      - fix/*
      - hotfix/*
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build and Test Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      # Use the authenticated token
      - name: Use authenticated token
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          echo "Authenticated as a GitHub App"
          # Example: List branches in the repository
          gh api repos/:owner/:repo/branches --header "Authorization: token GH_TOKEN"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        # do not validate wrappers for now as this seems to fail consistently
        with:
          # do not validate wrappers for now as this seems to fail consistently
          validate-wrappers: false

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
